---
#############################################
### STAGING (DEV/UAT) Environment DCI ###
#############################################
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dci-svcaccount
  namespace: monitoring