---
##################################################
### STAGING (DEV/UAT) Environment DCI ###
##################################################
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-dci-access-binding
  namespace: monitoring
subjects:
  - kind: Group
    name: engineering:ops
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: dci-svcaccount
roleRef:
  kind: Role
  name: ops-dci-access
  apiGroup: rbac.authorization.k8s.io