#############################################
### STAGING (DEV/UAT) Environment DCI ###
#############################################
apiVersion: v1
kind: Namespace
metadata:
  name: dci
  labels:
    app.kubernetes.io/name: dci
    app.kubernetes.io/instance: dci

---
apiVersion: v1
kind: Secret
metadata:
  name: dci-cred
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.8
    app.kubernetes.io/instance: dci-dev_db
    app.kubernetes.io/managed-by: Helm
  namespace: monitoring
type: Opaque
data:
  db-user: dXNlcm5hbWUK   # username
  db-pass: cGFzc3cwcmQK   # passw0rd
  db-host: MTI3LjAuMC4xCg==  # 127.0.0.1